### ISSUE TITLE
generarea receptiei din aviz nu incarca stocul pentru articolele receptionate

### ISSUE THREAD

**Issue by andreicorbu** [SoftulmeuRo/mbcstocuri#1]
Pasul 1)
      
- Am creat un Aviz din fereastra “Documente -> Avize de expeditie”.
- Am completat toate campurile dupa care am salvat:

![1](https://cloud.githubusercontent.com/assets/12709454/7930574/39186402-0912-11e5-92a7-3ef42dbe961b.png)

Pasul 2)	
- Avizul a aparut in fereastra “Stocuri -> Iesiri”.

![2](https://cloud.githubusercontent.com/assets/12709454/7930594/71780910-0912-11e5-88c9-89e8eaab3553.png)

Pasul 3)	
- Am generat un raport din fereastra “Rapoarte -> Pregatire Stocuri”.
- Am constatat ca produsul respective a fost scos din stoc:

 
![3](https://cloud.githubusercontent.com/assets/12709454/7930598/76d7b5b8-0912-11e5-888e-847ca2e8b2dd.png)

Pasul 4)	
- M-am intors pe avizul nou creat in fereastra “Documente -> Avize de expeditie -> deschide”.
- Am incercat sa generez o Receptie pentru acest aviz din butonul “Genereaza receptie”:

 
![4](https://cloud.githubusercontent.com/assets/12709454/7930599/7b67a750-0912-11e5-9e6e-af471e447f24.png)

Pasul 5)
- Am salvat receptia creata:

 
![5](https://cloud.githubusercontent.com/assets/12709454/7930603/800f6be4-0912-11e5-8581-4c9dfd768ead.png)

Pasul 6)	
- Insa aceasta receptie nu imi apare in fereastra “Stocuri -> Intrari”. 
- Totodata daca ma uit in fereastra “Rapoarte -> Pregatire Stocuri” pot observa ca stocul pentru produsul respective nu s-a modificat:

 
![6](https://cloud.githubusercontent.com/assets/12709454/7930606/837aa280-0912-11e5-865f-4452a864bf9d.png)

Pasul 7)	
- Daca ma duc in fereastra “Documente -> Lista receptii” pot sa observa ca in aceasta fereastra mi s-a salvat receptia creat pentru acel aviz:

![7](https://cloud.githubusercontent.com/assets/12709454/7930610/885df84c-0912-11e5-8a42-550e0b7c4d38.png)

**Comment by t1b1c** [comment]
rezolvat
